
## github simple workflow
name: Simple workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run command
        run: echo "Hello, World!"
  
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Run command
        run: echo "This is a test job."

  